# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbc31734886d97747c39ba74d80422faa197b710843312f310742112b226d48f54f34d499f355640cb3a909af56d2e839876d3d0a566ec9256dd0a39848d1e93

test:
  secret_key_base: 52f553aca6480930b7ab5a28e771f7cbb4b1198c75bcdeea47228cc5f4ac402455e2d316554213bd1ba1c4146d6570c6c6c3d656f47b90ee0236b736c920e038

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
